package org.fruct.oss.audioguide.track;

import android.location.Location;
import android.os.Parcel;
import android.os.Parcelable;

public class Point implements Parcelable {
	private String name;
	private String description;
	private int latE6;
	private int lonE6;

	private String audioUrl;
	private String photoUrl;

	private transient Location cachedLocation;

	public Point(String name, String description, String audioUrl, String photoUrl, int latE6, int lonE6) {
		this.name = name;
		this.description = description;
		this.audioUrl = audioUrl;
		this.latE6 = latE6;
		this.lonE6 = lonE6;
		this.photoUrl = photoUrl;
	}

	public Point(String name, String description, String audioUrl, int latE6, int lonE6) {
		this(name, description, audioUrl, "", latE6, lonE6);
	}

	public Point(String name, String description, String audioUrl, double lat, double lon) {
		this(name, description, audioUrl, "", lat, lon);
	}

	public Point(String name, String description, String audioUrl, String photoUrl, double lat, double lon) {
		this(name, description, audioUrl, photoUrl, (int)(lat * 1e6), (int)(lon * 1e6));
	}


	public String getName() {
		return name;
	}

	public String getDescription() {
		return description;
	}

	public String getAudioUrl() {
		return audioUrl;
	}

	public String getPhotoUrl() {
		return photoUrl;
	}

	public int getLatE6() {
		cachedLocation = null;
		return latE6;
	}

	public int getLonE6() {
		cachedLocation = null;
		return lonE6;
	}

	public Location toLocation() {
		if (cachedLocation != null)
			return cachedLocation;

		Location loc = new Location("empty-provider");

		loc.setLatitude(latE6 / 1e6);
		loc.setLongitude(lonE6 / 1e6);

		return cachedLocation = loc;
	}

	public boolean hasAudio() {
		return audioUrl != null && !audioUrl.isEmpty();
	}

	public boolean hasPhoto() {
		return photoUrl != null && !photoUrl.isEmpty();
	}

	// Generated by IDEA

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;

		Point point = (Point) o;

		if (latE6 != point.latE6) return false;
		if (lonE6 != point.lonE6) return false;
		if (audioUrl != null ? !audioUrl.equals(point.audioUrl) : point.audioUrl != null)
			return false;
		if (description != null ? !description.equals(point.description) : point.description != null)
			return false;
		if (name != null ? !name.equals(point.name) : point.name != null) return false;
		if (photoUrl != null ? !photoUrl.equals(point.photoUrl) : point.photoUrl != null)
			return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = name != null ? name.hashCode() : 0;
		result = 31 * result + (description != null ? description.hashCode() : 0);
		result = 31 * result + latE6;
		result = 31 * result + lonE6;
		result = 31 * result + (audioUrl != null ? audioUrl.hashCode() : 0);
		result = 31 * result + (photoUrl != null ? photoUrl.hashCode() : 0);
		return result;
	}

	// End generated by IDEA

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel parcel, int i) {
		parcel.writeString(name);
		parcel.writeString(description);
		parcel.writeString(audioUrl);

		parcel.writeInt(latE6);
		parcel.writeInt(lonE6);

		parcel.writeString(photoUrl);
	}

	public static final Creator<Point> CREATOR = new Creator<Point>() {
		@Override
		public Point createFromParcel(Parcel parcel) {
			String name = parcel.readString();
			String desc = parcel.readString();
			String audioUrl = parcel.readString();
			int latE6 = parcel.readInt();
			int lonE6 = parcel.readInt();

			String photoUrl = parcel.readString();

			return new Point(name, desc, audioUrl, photoUrl, latE6, lonE6);
		}

		@Override
		public Point[] newArray(int i) {
			return new Point[i];
		}
	};
}
